version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: sandr
      POSTGRES_PASSWORD: sandr
      POSTGRES_DB: triviadb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL: postgresql://sandr:sandr@db:5432/trivia_db
    