version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: sandr
      POSTGRES_PASSWORD: sandr
      POSTGRES_DB: db
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL: 
    