name: Python CI

on:
  push:
    branches: [develop, main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt
      - run: PYTHONPATH=. pytest
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: > 
            -Dsonar.organization=sandrocj210
            -Dsonar.projectKey=SandroCJ210_Entry-Test-SD
            -Dsonar.sources=app/
            -Dsonar.tests=tests/
      - name: Run Security Scan
        run: bandit -r ./app